# Generated by Django 4.0 on 2024-12-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityapp', '0003_rename_number_of_people_bookings_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
