# Generated by Django 5.1.4 on 2024-12-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityapp', '0006_feedback_delete_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='default_name', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='occupation',
            field=models.CharField(default='default_occupation', max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
