# Generated by Django 5.1.4 on 2024-12-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityapp', '0007_feedback_name_feedback_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='occupation',
            field=models.CharField(max_length=255),
        ),
    ]
